# Generated by Django 3.2.6 on 2022-06-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taskprovider',
        ),
    ]
