# Generated by Django 3.2.6 on 2022-06-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprovider',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
