# Generated by Django 4.0.1 on 2022-06-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskprovider_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprovider',
            name='process',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskprovider',
            name='requested_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskprovider',
            name='requested_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
