# Generated by Django 3.2.6 on 2022-06-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_taskprovider_process_taskprovider_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprovider',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=0),
        ),
    ]
