# Generated by Django 3.2.6 on 2022-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_status_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_task',
            name='completeddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
