# Generated by Django 4.0.1 on 2022-06-09 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_status_task_completeddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_task',
            name='title',
        ),
        migrations.AddField(
            model_name='status_task',
            name='taskprovider',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='task.taskprovider'),
            preserve_default=False,
        ),
    ]
