# Generated by Django 3.2.6 on 2022-06-10 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_remove_status_task_title_status_task_taskprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='overall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.employee')),
                ('status_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.status_task')),
                ('taskprovider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.taskprovider')),
            ],
        ),
    ]
