# Generated by Django 3.2.6 on 2022-06-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_overall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='overall',
        ),
    ]
